# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TxFApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TxFApp.Class')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], max_length=1)),
                ('location', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('reward', models.CharField(blank=True, max_length=1000, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupxattendance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupxattendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupxclass',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupxclass',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='andrew_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='GroupX',
        ),
        migrations.DeleteModel(
            name='GroupXAttendance',
        ),
        migrations.DeleteModel(
            name='GroupXClass',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='class_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TxFApp.ClassType'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TxFApp.Profile'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TxFApp.ClassSchedule'),
        ),
    ]
