# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TxFApp', '0002_auto_20161015_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_schedule_id',
            new_name='class_schedule',
        ),
        migrations.RenameField(
            model_name='classattendance',
            old_name='class_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='classattendance',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='class_type_id',
            new_name='class_type',
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=15),
        ),
    ]
