# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TxFApp', '0003_auto_20161018_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
