# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TxFApp', '0006_auto_20161101_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='andrew_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
